# Site settings
title: Paolo Almeida
email: dev.paoloalmeida@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paoloalmeida.com" # the base hostname & protocol for your site
twitter_username: paolo_almeida
github_username:  paoloalmeida

# Build settings
markdown: kramdown
